version: '3'

networks:
    laravel:

services:
    # the web server
    nginx:
        image: nginx:stable-alpine
        container_name: laravel-nginx
        ports:
            - "8088:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mariadb
        networks:
            - laravel
    # the database
    mariadb:
        image: mariadb
        container_name: laravel-mariadb
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - ./mariadb:/var/lib/mariadb
        environment:
            MYSQL_DATABASE: podcast_statistics
            MYSQL_USER: podcaster
            MYSQL_PASSWORD: podcasting
            MYSQL_ROOT_PASSWORD: podcasting
        networks:
            - laravel
    # the language.
    php:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: laravel-php
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel
